import type { Locale } from "@/lib/i18n/locales";

const en = {
  title: "Cover letter generator",
  subtitle: "Tailored to the job — with AI suggestions in flowing text.",
  step: "Step",
  of: "of",
  stepJob: "Job & data",
  stepIdeas: "AI suggestions",
  stepReview: "Review & download",
  position: "Position",
  positionPlaceholder: "e.g. Nursing specialist",
  company: "Company",
  companyPlaceholder: "e.g. Muster GmbH",
  recipient: "Contact person (optional)",
  recipientPlaceholder: "e.g. Ms Schmidt",
  address: "Company address (optional)",
  addressPlaceholder: "Street, postcode, city",
  jobAd: "Job advert (optional)",
  jobAdPlaceholder: "Paste the advert so the letter fits the job exactly.",
  yourData: "Your data",
  yourDataHint: "Prefilled from your CV — change anything you like.",
  fullName: "Full name",
  email: "Email",
  phone: "Phone",
  location: "City",
  tone: "Tone",
  toneProfessional: "Professional",
  toneWarm: "Warm",
  toneConfident: "Confident",
  next: "Continue",
  back: "Back",
  needJob: "Please enter position and company.",
  ideasTitle: "Pick the arguments that apply to you",
  ideasHint: "Each suggestion is one short sentence. You can edit everything later.",
  reload: "Reload",
  loading: "The AI is looking for matching arguments …",
  notes: "Your own notes (optional)",
  notesPlaceholder: "Anything the AI should mention.",
  generate: "Generate cover letter",
  generating: "Writing your cover letter …",
  regenerate: "Regenerate",
  editable: "Cover letter (editable)",
  editableHint: "Change the text here, or download it as Word and edit it in your writing app.",
  downloadWord: "Download as Word",
  downloadPdf: "Download as PDF",
  approve: "Text is fine — download PDF",
  sendMail: "Send as email",
  mailPrepared: "PDF downloaded — attach it to the email that just opened.",
  created: "Cover letter created",
  failed: "The cover letter could not be created. Please try again.",
  suggestionsFailed: "The suggestions could not be loaded.",
  signIn: "Sign in",
  signInText: "Sign in so the AI can create your personal cover letter.",
  docLanguage: "Letter language",
  empty: "Your cover letter will appear here.",
  preview: "Live preview",
};

type Copy = typeof en;

const de: Copy = {
  title: "Anschreiben-Generator",
  subtitle: "Passend zur Stelle — mit KI-Vorschlägen in fließendem Kurztext.",
  step: "Schritt",
  of: "von",
  stepJob: "Stelle & Daten",
  stepIdeas: "KI-Vorschläge",
  stepReview: "Prüfen & herunterladen",
  position: "Position",
  positionPlaceholder: "z. B. Pflegefachkraft",
  company: "Unternehmen",
  companyPlaceholder: "z. B. Muster GmbH",
  recipient: "Ansprechpartner (optional)",
  recipientPlaceholder: "z. B. Frau Schmidt",
  address: "Firmenadresse (optional)",
  addressPlaceholder: "Straße, PLZ, Ort",
  jobAd: "Stellenanzeige (optional)",
  jobAdPlaceholder: "Füge die Anzeige ein, damit das Anschreiben exakt passt.",
  yourData: "Deine Daten",
  yourDataHint: "Aus deinem Lebenslauf übernommen — du kannst alles ändern.",
  fullName: "Vollständiger Name",
  email: "E-Mail",
  phone: "Telefon",
  location: "Ort",
  tone: "Tonalität",
  toneProfessional: "Sachlich",
  toneWarm: "Herzlich",
  toneConfident: "Selbstbewusst",
  next: "Weiter",
  back: "Zurück",
  needJob: "Bitte gib Position und Unternehmen an.",
  ideasTitle: "Wähle die Argumente, die auf dich zutreffen",
  ideasHint: "Jeder Vorschlag ist ein kurzer Satz. Du kannst später alles bearbeiten.",
  reload: "Neu laden",
  loading: "Die KI sucht passende Argumente …",
  notes: "Eigene Hinweise (optional)",
  notesPlaceholder: "Was die KI zusätzlich erwähnen soll.",
  generate: "Anschreiben erstellen",
  generating: "Dein Anschreiben wird geschrieben …",
  regenerate: "Neu erstellen",
  editable: "Anschreiben (bearbeitbar)",
  editableHint:
    "Ändere den Text hier direkt — oder lade ihn als Word herunter und bearbeite ihn in deinem Schreibprogramm.",
  downloadWord: "Als Word herunterladen",
  downloadPdf: "Als PDF herunterladen",
  approve: "Text passt — PDF herunterladen",
  sendMail: "Als E-Mail senden",
  mailPrepared: "PDF heruntergeladen — hänge es an die geöffnete E-Mail an.",
  created: "Anschreiben erstellt",
  failed: "Das Anschreiben konnte nicht erstellt werden. Bitte erneut versuchen.",
  suggestionsFailed: "Die Vorschläge konnten nicht geladen werden.",
  signIn: "Jetzt anmelden",
  signInText: "Melde dich an, damit die KI dein persönliches Anschreiben erstellen kann.",
  docLanguage: "Sprache des Anschreibens",
  empty: "Dein Anschreiben erscheint hier.",
  preview: "Live-Vorschau",
};

const fr: Copy = {
  ...en,
  title: "Générateur de lettre de motivation",
  subtitle: "Adaptée au poste — avec des suggestions IA en texte fluide.",
  step: "Étape",
  of: "sur",
  stepJob: "Poste et données",
  stepIdeas: "Suggestions IA",
  stepReview: "Vérifier et télécharger",
  position: "Poste",
  company: "Entreprise",
  recipient: "Interlocuteur (facultatif)",
  address: "Adresse de l'entreprise (facultatif)",
  jobAd: "Offre d'emploi (facultatif)",
  yourData: "Vos données",
  yourDataHint: "Reprises de votre CV — modifiables à tout moment.",
  fullName: "Nom complet",
  email: "E-mail",
  phone: "Téléphone",
  location: "Ville",
  tone: "Ton",
  next: "Continuer",
  back: "Retour",
  ideasTitle: "Choisissez les arguments qui vous correspondent",
  reload: "Recharger",
  loading: "L'IA cherche des arguments adaptés …",
  notes: "Vos remarques (facultatif)",
  generate: "Créer la lettre",
  generating: "Rédaction en cours …",
  regenerate: "Régénérer",
  editable: "Lettre (modifiable)",
  downloadWord: "Télécharger en Word",
  downloadPdf: "Télécharger en PDF",
  approve: "Le texte convient — télécharger le PDF",
  sendMail: "Envoyer par e-mail",
  mailPrepared: "PDF téléchargé — joignez-le à l'e-mail ouvert.",
  created: "Lettre créée",
  docLanguage: "Langue de la lettre",
  preview: "Aperçu en direct",
};

const es: Copy = {
  ...en,
  title: "Generador de carta de presentación",
  subtitle: "Adaptada al puesto — con sugerencias de IA en texto fluido.",
  step: "Paso",
  of: "de",
  stepJob: "Puesto y datos",
  stepIdeas: "Sugerencias de IA",
  stepReview: "Revisar y descargar",
  position: "Puesto",
  company: "Empresa",
  recipient: "Persona de contacto (opcional)",
  address: "Dirección de la empresa (opcional)",
  jobAd: "Oferta de empleo (opcional)",
  yourData: "Tus datos",
  fullName: "Nombre completo",
  email: "Correo",
  phone: "Teléfono",
  location: "Ciudad",
  tone: "Tono",
  next: "Continuar",
  back: "Atrás",
  ideasTitle: "Elige los argumentos que se ajusten a ti",
  reload: "Recargar",
  loading: "La IA busca argumentos adecuados …",
  notes: "Notas propias (opcional)",
  generate: "Crear carta",
  generating: "Escribiendo tu carta …",
  regenerate: "Volver a generar",
  editable: "Carta (editable)",
  downloadWord: "Descargar en Word",
  downloadPdf: "Descargar en PDF",
  approve: "El texto está bien — descargar PDF",
  sendMail: "Enviar por correo",
  mailPrepared: "PDF descargado: adjúntalo al correo que se ha abierto.",
  created: "Carta creada",
  docLanguage: "Idioma de la carta",
  preview: "Vista previa",
};

const ar: Copy = {
  ...en,
  title: "مولّد رسالة التقديم",
  subtitle: "مخصصة للوظيفة — مع اقتراحات ذكاء اصطناعي بنص قصير ومترابط.",
  step: "الخطوة",
  of: "من",
  stepJob: "الوظيفة والبيانات",
  stepIdeas: "اقتراحات الذكاء الاصطناعي",
  stepReview: "المراجعة والتنزيل",
  position: "الوظيفة",
  company: "الشركة",
  recipient: "جهة الاتصال (اختياري)",
  address: "عنوان الشركة (اختياري)",
  jobAd: "إعلان الوظيفة (اختياري)",
  yourData: "بياناتك",
  fullName: "الاسم الكامل",
  email: "البريد الإلكتروني",
  phone: "الهاتف",
  location: "المدينة",
  tone: "الأسلوب",
  next: "متابعة",
  back: "رجوع",
  ideasTitle: "اختر الحجج التي تنطبق عليك",
  reload: "إعادة التحميل",
  loading: "يبحث الذكاء الاصطناعي عن حجج مناسبة …",
  notes: "ملاحظاتك (اختياري)",
  generate: "إنشاء رسالة التقديم",
  generating: "يتم كتابة رسالتك …",
  regenerate: "إنشاء من جديد",
  editable: "الرسالة (قابلة للتعديل)",
  downloadWord: "تنزيل كملف Word",
  downloadPdf: "تنزيل كملف PDF",
  approve: "النص مناسب — تنزيل PDF",
  sendMail: "إرسال بالبريد الإلكتروني",
  mailPrepared: "تم تنزيل ملف PDF — أرفقه بالبريد المفتوح.",
  created: "تم إنشاء الرسالة",
  docLanguage: "لغة الرسالة",
  preview: "معاينة مباشرة",
};

export const coverCopy: Record<Locale, Copy> = {
  de,
  en,
  fr,
  es,
  ar,
  it: en,
  nl: en,
};
