import type { Locale } from "@/lib/i18n/locales";

const en = {
  title: "My templates",
  subtitle: "Upload your own design (image or PDF), keep it private and pick it as a reference.",
  upload: "Upload template",
  uploading: "Uploading …",
  name: "Name",
  namePlaceholder: "e.g. Blue two-column",
  note: "Note (optional)",
  notePlaceholder: "What do you like about this layout?",
  file: "File (JPG, PNG, WebP or PDF, max. 10 MB)",
  empty: "No templates yet. Upload your first design.",
  select: "Use as reference",
  selected: "Selected",
  remove: "Delete",
  open: "Open",
  loginTitle: "Sign in required",
  loginText: "Your templates are private, so please sign in first.",
  login: "Sign in",
  backEditor: "Back to editor",
  errName: "Please enter a name.",
  errFile: "Please choose a file.",
  errType: "Only JPG, PNG, WebP or PDF are allowed.",
  errSize: "The file is larger than 10 MB.",
  saved: "Template saved.",
  deleted: "Template deleted.",
  failed: "Something went wrong. Please try again.",
  pdf: "PDF document",
};

type Copy = typeof en;

const de: Copy = {
  title: "Meine Vorlagen",
  subtitle: "Lade dein eigenes Design (Bild oder PDF) hoch, privat gespeichert und als Referenz wählbar.",
  upload: "Vorlage hochladen",
  uploading: "Wird hochgeladen …",
  name: "Name",
  namePlaceholder: "z. B. Blau zweispaltig",
  note: "Notiz (optional)",
  notePlaceholder: "Was gefällt dir an diesem Layout?",
  file: "Datei (JPG, PNG, WebP oder PDF, max. 10 MB)",
  empty: "Noch keine Vorlagen. Lade dein erstes Design hoch.",
  select: "Als Referenz nutzen",
  selected: "Ausgewählt",
  remove: "Löschen",
  open: "Öffnen",
  loginTitle: "Anmeldung nötig",
  loginText: "Deine Vorlagen sind privat – bitte melde dich zuerst an.",
  login: "Anmelden",
  backEditor: "Zurück zum Editor",
  errName: "Bitte gib einen Namen ein.",
  errFile: "Bitte wähle eine Datei.",
  errType: "Erlaubt sind nur JPG, PNG, WebP oder PDF.",
  errSize: "Die Datei ist größer als 10 MB.",
  saved: "Vorlage gespeichert.",
  deleted: "Vorlage gelöscht.",
  failed: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
  pdf: "PDF-Dokument",
};

const fr: Copy = {
  title: "Mes modèles",
  subtitle: "Téléverse ton propre design (image ou PDF), stocké en privé et sélectionnable comme référence.",
  upload: "Téléverser un modèle",
  uploading: "Téléversement …",
  name: "Nom",
  namePlaceholder: "p. ex. Bleu deux colonnes",
  note: "Note (facultatif)",
  notePlaceholder: "Ce qui te plaît dans cette mise en page.",
  file: "Fichier (JPG, PNG, WebP ou PDF, max. 10 Mo)",
  empty: "Aucun modèle pour l'instant. Téléverse ton premier design.",
  select: "Utiliser comme référence",
  selected: "Sélectionné",
  remove: "Supprimer",
  open: "Ouvrir",
  loginTitle: "Connexion requise",
  loginText: "Tes modèles sont privés – connecte-toi d'abord.",
  login: "Se connecter",
  backEditor: "Retour à l'éditeur",
  errName: "Merci d'indiquer un nom.",
  errFile: "Merci de choisir un fichier.",
  errType: "Seuls JPG, PNG, WebP ou PDF sont autorisés.",
  errSize: "Le fichier dépasse 10 Mo.",
  saved: "Modèle enregistré.",
  deleted: "Modèle supprimé.",
  failed: "Une erreur est survenue. Réessaie.",
  pdf: "Document PDF",
};

const es: Copy = {
  title: "Mis plantillas",
  subtitle: "Sube tu propio diseño (imagen o PDF), guardado en privado y seleccionable como referencia.",
  upload: "Subir plantilla",
  uploading: "Subiendo …",
  name: "Nombre",
  namePlaceholder: "p. ej. Azul a dos columnas",
  note: "Nota (opcional)",
  notePlaceholder: "Qué te gusta de este diseño.",
  file: "Archivo (JPG, PNG, WebP o PDF, máx. 10 MB)",
  empty: "Aún no hay plantillas. Sube tu primer diseño.",
  select: "Usar como referencia",
  selected: "Seleccionada",
  remove: "Eliminar",
  open: "Abrir",
  loginTitle: "Inicio de sesión necesario",
  loginText: "Tus plantillas son privadas: inicia sesión primero.",
  login: "Iniciar sesión",
  backEditor: "Volver al editor",
  errName: "Introduce un nombre.",
  errFile: "Elige un archivo.",
  errType: "Solo se permiten JPG, PNG, WebP o PDF.",
  errSize: "El archivo supera 10 MB.",
  saved: "Plantilla guardada.",
  deleted: "Plantilla eliminada.",
  failed: "Algo salió mal. Inténtalo de nuevo.",
  pdf: "Documento PDF",
};

const ar: Copy = {
  title: "قوالبي",
  subtitle: "ارفع تصميمك الخاص (صورة أو PDF)، محفوظ بشكل خاص ويمكن اختياره كمرجع.",
  upload: "رفع قالب",
  uploading: "جارٍ الرفع …",
  name: "الاسم",
  namePlaceholder: "مثال: أزرق بعمودين",
  note: "ملاحظة (اختياري)",
  notePlaceholder: "ما الذي يعجبك في هذا التصميم؟",
  file: "ملف (JPG أو PNG أو WebP أو PDF، بحد أقصى 10 ميغابايت)",
  empty: "لا توجد قوالب بعد. ارفع تصميمك الأول.",
  select: "استخدام كمرجع",
  selected: "محدد",
  remove: "حذف",
  open: "فتح",
  loginTitle: "تسجيل الدخول مطلوب",
  loginText: "قوالبك خاصة – يرجى تسجيل الدخول أولاً.",
  login: "تسجيل الدخول",
  backEditor: "العودة إلى المحرر",
  errName: "يرجى إدخال اسم.",
  errFile: "يرجى اختيار ملف.",
  errType: "المسموح فقط JPG أو PNG أو WebP أو PDF.",
  errSize: "حجم الملف أكبر من 10 ميغابايت.",
  saved: "تم حفظ القالب.",
  deleted: "تم حذف القالب.",
  failed: "حدث خطأ ما. حاول مرة أخرى.",
  pdf: "مستند PDF",
};

const it: Copy = {
  ...en,
  title: "I miei modelli",
  subtitle: "Carica il tuo design (immagine o PDF), salvato in privato e selezionabile come riferimento.",
  upload: "Carica modello",
  uploading: "Caricamento …",
  name: "Nome",
  select: "Usa come riferimento",
  selected: "Selezionato",
  remove: "Elimina",
  open: "Apri",
  empty: "Ancora nessun modello. Carica il tuo primo design.",
  backEditor: "Torna all'editor",
};

const nl: Copy = {
  ...en,
  title: "Mijn sjablonen",
  subtitle: "Upload je eigen ontwerp (afbeelding of PDF), privé opgeslagen en te kiezen als referentie.",
  upload: "Sjabloon uploaden",
  uploading: "Uploaden …",
  name: "Naam",
  select: "Als referentie gebruiken",
  selected: "Geselecteerd",
  remove: "Verwijderen",
  open: "Openen",
  empty: "Nog geen sjablonen. Upload je eerste ontwerp.",
  backEditor: "Terug naar editor",
};

const copies: Record<Locale, Copy> = { de, en, fr, es, ar, it, nl };

export function templateCopy(locale: Locale): Copy {
  return copies[locale] ?? de;
}
